"use client";
import { frontendContainer } from "@/container";
import { DeleteTestRequestCommand, testRequestModuleNames } from "@/modules/TestRequests";
import { MutationErrorProvider } from "@/hooks/mutation-error-context";
import { useManagedMutation } from "@/hooks/use-managed-mutation";
import { PropsWithChildren } from "react";
import { useMirrorRegistry } from "./store";
const command = frontendContainer.get<DeleteTestRequestCommand>(testRequestModuleNames.deleteTestRequestCommand);
const Api = ({children}: PropsWithChildren) => { const mutation=useManagedMutation({mutationFn:async(id:string)=>{command.init({id}); return command.exec();}}); useMirrorRegistry("submitAction",mutation.mutateAsync); return <MutationErrorProvider>{children}</MutationErrorProvider>;};
export { Api };
